version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: larussoauto
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql
    restart: always
    